name = "HespanhaRegistry.jl"
uuid = "951af33b-d96e-4957-8eea-3a9aff55af0e"
repo = "https://github.com/HespanhaPublic/HespanhaRegistry.jl"
description = "Joao Hespanha's registry for julia packages"

[packages]
26f64549-84f9-45a4-806b-e6e7796e7b6b = { name = "EstimationTools", path = "E/EstimationTools" }
